name: helloworld
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.8  # Updated to a compatible version
  firebase_core: ^2.27.0    # Updated to a compatible version
  firebase_auth: ^4.6.3
  firebase_storage: ^11.6.9
  image_picker: ^0.8.7+4
  firebase_messaging: ^14.7.19
  provider: ^6.1.2
  intl: ^0.17.0
  uuid: ^3.0.6
  flutter_local_notifications: ^17.2.1+1
  google_maps_flutter: ^2.5.3
  http: ^1.2.1
  flutter_stripe: ^4.0.0
  geolocator: ^9.0.0
  permission_handler: ^10.2.0 
  ticket_widget: ^0.0.1
  barcode_widget: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.0.6
  flutterwave_standard: ^1.0.5 
  qr_flutter: ^4.1.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  printing: ^5.12.0
  flutter_file_dialog: ^3.0.2
  screenshot: ^2.5.0
 
 




dev_dependencies:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0     # Updated to a compatible version
  bdd_widget_test: ^1.2.1
  build_runner: ^2.4.9
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
 

  assets:
    - assets/images/background1.jpeg
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #  , - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700